name: task_manager_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_route: '7.7.1'
  bloc: ^8.1.2
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  dio: ^5.4.2+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2

dev_dependencies:
  auto_route_generator: '7.2.0'
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
